name: Tests

on:
  push:
    paths-ignore:
      - "**.md"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 2

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@main
      - name: Run Iamshankhadeep/setup-ffmpeg
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Iamshankhadeep/setup-ffmpeg
        id: setup-ffmpeg
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: ffmpeg -version
      - run: ffprobe -version
